name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        gemfile: [websocket-driver-0.6.x, websocket-driver-0.7.x]
        ruby: [2.6, 2.7, 3.0, 3.1]
    runs-on: ubuntu-latest
    env:
      FERRUM_PROCESS_TIMEOUT: 20
      FERRUM_DEFAULT_TIMEOUT: 15
      BUNDLE_GEMFILE: .github/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - run: mkdir -p /tmp/cuprite

      - name: Run tests
        run: bundle exec rake
        if: |
          !contains(github.event.pull_request.labels.*.name, 'master')

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: footprints
          path: /tmp/cuprite/
